- hosts: all
  become: true
  roles:
    - role: commons

- hosts: nodo1
  become: true
  roles:
    - role: router
    - role: dhcp

- hosts: cliente1
  become: true
  roles:
    - role: cliente
    - role: web

- hosts: cliente2
  become: true
  roles:
    - role: cliente
